name: CI/CD build release for Linux macOS Windows
on:
  push:
    branches: [ main, devel ]
    tags:
      - "*"
jobs:
  build-linux:
    name: 'Build Linux'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        sudo apt-get -y -q update && sudo apt-get -y -q upgrade
        sudo apt-get -y -q install g++-10-i686-linux-gnu
        sudo apt-get -y -q install g++-10-arm-linux-gnueabihf
        sudo apt-get -y -q install g++-10-aarch64-linux-gnu
        #
        i686-linux-gnu-g++-10 noso-2m.cpp md5-c.cpp -o noso-2m-i686 -std=c++20 -Ofast -lpthread
        i686-linux-gnu-strip -s noso-2m-i686
        file noso-2m-i686
        #
        x86_64-linux-gnu-g++-10 noso-2m.cpp md5-c.cpp -o noso-2m-x86_64 -std=c++20 -Ofast -lpthread
        x86_64-linux-gnu-strip -s noso-2m-x86_64
        file noso-2m-x86_64
        #
        arm-linux-gnueabihf-g++-10 noso-2m.cpp md5-c.cpp -o noso-2m-arm -std=c++20 -Ofast -lpthread
        arm-linux-gnueabihf-strip -s noso-2m-arm
        file noso-2m-arm
        #
        aarch64-linux-gnu-g++-10 noso-2m.cpp md5-c.cpp -o noso-2m-aarch64 -std=c++20 -Ofast -lpthread
        aarch64-linux-gnu-strip -s noso-2m-aarch64
        file noso-2m-aarch64
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'ubuntu-latest'
        path: |
          README.md
          noso-2m-i686
          noso-2m-x86_64
          noso-2m-arm
          noso-2m-aarch64
  build-windows:
    name: 'Build Windows'
    runs-on: 'windows-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        clang++ noso-2m.cpp md5-c.cpp -o noso-2m-i686.exe -std=c++20 -Ofast -target i686-pc-win32 -Wl,-machine:x86 -lWs2_32.lib -static
        clang++ noso-2m.cpp md5-c.cpp -o noso-2m-x86_64.exe -std=c++20 -Ofast -target x86_64-pc-win32 -Wl,-machine:x64 -lWs2_32.lib -static
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'windows-latest'
        path: |
          README.md
          noso-2m-i686.exe
          noso-2m-x86_64.exe
  build-macos:
    name: 'Build macOS'
    runs-on: 'macos-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        g++ noso-2m.cpp md5-c.cpp -o noso-2m-darwin -std=c++20 -Ofast -lpthread
        strip -x noso-2m-darwin
        file noso-2m-darwin
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'macos-latest'
        path: |
          README.md
          noso-2m-darwin
  release-linux:
    if: contains(github.ref, '/tags/')
    name: 'Release ubuntu-latest'
    runs-on: 'ubuntu-latest'
    needs: [build-linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp ubuntu-latest/README.md README.md
          #
          cp ubuntu-latest/noso-2m-i686 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-i686.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-x86_64 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-x86_64.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-arm noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-arm.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-aarch64 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-aarch64.tar.gz noso-2m README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noso-2m-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-macos:
    if: contains(github.ref, '/tags/')
    name: 'Release macos-latest'
    runs-on: 'macos-latest'
    needs: [build-macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp macos-latest/README.md README.md
          cp macos-latest/noso-2m-darwin noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-darwin.tar.gz noso-2m README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noso-2m-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows:
    if: contains(github.ref, '/tags/')
    name: 'Release windows-latest'
    runs-on: 'windows-latest'
    needs: [build-windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp windows-latest/README.md README.md
          #
          cp windows-latest/noso-2m-x86_64.exe noso-2m.exe
          7z a -tzip noso-2m-${tag}-win64-x86_64.zip noso-2m.exe README.md
          #
          cp windows-latest/noso-2m-i686.exe noso-2m.exe
          7z a -tzip noso-2m-${tag}-win32-i686.zip noso-2m.exe README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noso-2m-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
