name: CI/CD build release for Linux macOS Windows
on:
  push:
    branches: [ main, devel ]
    tags:
      - "*"
jobs:
  build-linux:
    name: 'Build Linux'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        sudo apt-get -y -qq update && sudo apt-get -y -q upgrade
        sudo apt-get -y -qq install gcc-10-multilib g++-10-multilib
        sudo apt-get -y -qq install g++-10-i686-linux-gnu gcc-10-multilib-i686-linux-gnu g++-10-multilib-i686-linux-gnu
        sudo apt-get -y -qq install g++-10-arm-linux-gnueabihf gcc-10-multilib-arm-linux-gnueabihf g++-10-multilib-arm-linux-gnueabihf
        sudo apt-get -y -qq install g++-10-aarch64-linux-gnu
        wget -q https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip -qq android-ndk-r23b-linux.zip
        #
        # clang++ --target=i686-linux-gnu --sysroot=/usr/i686-linux-gnu \
        #   -I/usr/i686-linux-gnu/include/c++/10/i686-linux-gnu \
        #   noso-2m.cpp md5-c.cpp -o noso-2m-linux-i686 -std=c++20 -Ofast -lpthread -s
        i686-linux-gnu-g++-10 \
          noso-2m.cpp md5-c.cpp -o noso-2m-linux-i686 -std=c++20 -O3 -lpthread -s
        file noso-2m-linux-i686
        #
        clang++ \
          noso-2m.cpp md5-c.cpp -o noso-2m-linux-x86_64 -std=c++20 -Ofast -lpthread -s
        # x86_64-linux-gnu-g++-10 \
        #   noso-2m.cpp md5-c.cpp -o noso-2m-linux-x86_64 -std=c++20 -O3 -lpthread -s
        file noso-2m-linux-x86_64
        #
        # clang++ --target=arm-linux-gnueabihf --sysroot=/usr/arm-linux-gnueabihf \
        #   -I/usr/arm-linux-gnueabihf/include/c++/10/i686-linux-gnu \
        #   noso-2m.cpp md5-c.cpp -o noso-2m-linux-arm -std=c++20 -Ofast -lpthread -s
        arm-linux-gnueabihf-g++-10 \
          noso-2m.cpp md5-c.cpp -o noso-2m-linux-arm -std=c++20 -O3 -lpthread -s
        file noso-2m-linux-arm
        #
        # clang++ --target=aarch64-linux-gnu --sysroot=/usr/aarch64-linux-gnu \
        #   -I/usr/aarch64-linux-gnu/include/c++/10/aarch64-linux-gnu \
        #   noso-2m.cpp md5-c.cpp -o noso-2m-linux-aarch64 -std=c++20 -Ofast -lpthread -s
        aarch64-linux-gnu-g++-10 \
          noso-2m.cpp md5-c.cpp -o noso-2m-linux-aarch64 -std=c++20 -O3 -lpthread -s
        file noso-2m-linux-aarch64
        #
        android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi31-clang++ \
          noso-2m.cpp md5-c.cpp -o noso-2m-android-armv7a -std=c++20 -Ofast -static -s
        file noso-2m-android-armv7a
        #
        android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang++ \
          noso-2m.cpp md5-c.cpp -o noso-2m-android-aarch64 -std=c++20 -Ofast -static -s
        file noso-2m-android-aarch64
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'ubuntu-latest'
        path: |
          README.md
          noso-2m-linux-i686
          noso-2m-linux-x86_64
          noso-2m-linux-arm
          noso-2m-linux-aarch64
          noso-2m-android-armv7a
          noso-2m-android-aarch64
  build-windows:
    name: 'Build Windows'
    runs-on: 'windows-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        clang++ noso-2m.cpp md5-c.cpp -o noso-2m-i686.exe -std=c++20 -Ofast -target i686-pc-win32 -Wl,-machine:x86 -lWs2_32.lib -Wl,-s
        clang++ noso-2m.cpp md5-c.cpp -o noso-2m-x86_64.exe -std=c++20 -Ofast -target x86_64-pc-win32 -Wl,-machine:x64 -lWs2_32.lib -Wl,-s
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'windows-latest'
        path: |
          README.md
          noso-2m-i686.exe
          noso-2m-x86_64.exe
  build-macos:
    name: 'Build macOS'
    runs-on: 'macos-latest'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build source
      run: |
        clang++ noso-2m.cpp md5-c.cpp -o noso-2m-darwin -std=c++20 -Ofast -s -lpthread
        strip -x noso-2m-darwin
        file noso-2m-darwin
      shell: bash
    - name: Upload artifacs
      uses: actions/upload-artifact@v2
      with:
        name: 'macos-latest'
        path: |
          README.md
          noso-2m-darwin
  release-linux:
    if: contains(github.ref, '/tags/')
    name: 'Release ubuntu-latest'
    runs-on: 'ubuntu-latest'
    needs: [build-linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp ubuntu-latest/README.md README.md
          #
          cp ubuntu-latest/noso-2m-linux-i686 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-i686.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-linux-x86_64 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-x86_64.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-linux-arm noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-arm.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-linux-aarch64 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-linux-aarch64.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-android-armv7a noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-android-armv7a.tar.gz noso-2m README.md
          #
          cp ubuntu-latest/noso-2m-android-aarch64 noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-android-aarch64.tar.gz noso-2m README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noso-2m-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-macos:
    if: contains(github.ref, '/tags/')
    name: 'Release macos-latest'
    runs-on: 'macos-latest'
    needs: [build-macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp macos-latest/README.md README.md
          cp macos-latest/noso-2m-darwin noso-2m
          chmod +x noso-2m
          tar -zcvf noso-2m-${tag}-darwin.tar.gz noso-2m README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noso-2m-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows:
    if: contains(github.ref, '/tags/')
    name: 'Release windows-latest'
    runs-on: 'windows-latest'
    needs: [build-windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Package artifacts
        run: |
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          cp windows-latest/README.md README.md
          #
          cp windows-latest/noso-2m-x86_64.exe noso-2m.exe
          7z a -tzip noso-2m-${tag}-win64-x86_64.zip noso-2m.exe README.md
          #
          cp windows-latest/noso-2m-i686.exe noso-2m.exe
          7z a -tzip noso-2m-${tag}-win32-i686.zip noso-2m.exe README.md
        shell: bash
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            noso-2m-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
