name: C/C++ CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: clang++ noso-2m.cpp md5-c.cpp -o noso-2m -std=c++20 -lpthread -Ofast
    - name: strip
      run: strip -s noso-2m
    - name: runone
      run: ./noso-2m --help
